#==========================================================================
# Description: Packaging OpenWrt
# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
# Copyright (C) 2021 https://github.com/ophub/flippy-openwrt-actions
#==========================================================================

name: Packaging OpenWrt

on:
  schedule:
    - cron: '20 20 * * *'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_soc:
        description: "Select device board."
        required: false
        default: "beikeyun"
        type: choice
        options:
          - beikeyun
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.85_6.1.1"
        type: choice
        options:
#          - 5.4.225_5.10.160_5.15.85
#          - 5.4.225_5.10.160
#          - 5.10.160_5.15.85
          - 5.15.85_6.1.1
#          - 5.4.225
#          - 5.10.160
          - 5.15.85
          - 6.1.1
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: false
        type: boolean

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}
      - name: Download armvirt file
        id: download
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          # Custom repository and Releases keywords for *rootfs.tar.gz file
          armvirt_rootfsfile_repo="ophub/amlogic-s9xxx-openwrt"
          releases_tag_keywords="OpenWrt_.*lede.*/.*rootfs.tar.gz"
          # The following download paths, etc. can remain unchanged
          save_rootfsfile_path="openwrt/bin/targets/armvirt/64"
          [[ -d "${save_rootfsfile_path}" ]] || mkdir -p ${save_rootfsfile_path}
          # Get the *rootfs.tar.gz file download address
          openwrt_url="$(curl \
                            --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                            -s "https://api.github.com/repos/${armvirt_rootfsfile_repo}/releases" |
                            grep -oE "${releases_tag_keywords}" | head -n 1
                        )"
          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
          down_file="https://github.com/${armvirt_rootfsfile_repo}/releases/download/${openwrt_url}"
          # Download the *rootfs.tar.gz file to the specified directory
          wget -q -P "${save_rootfsfile_path}" "${down_file}"
          [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
          echo "status=success" >> ${GITHUB_OUTPUT}
      - name: Package OpenWrt Firmware
        uses: ophub/flippy-openwrt-actions@main
        if: ${{ steps.download.outputs.status }} == 'success' && !cancelled()
        env:
          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
          PACKAGE_SOC: ${{ inputs.openwrt_soc }}
          KERNEL_VERSION_NAME: ${{ inputs.openwrt_kernel }}
          KERNEL_AUTO_LATEST: ${{ inputs.auto_kernel }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: OpenWrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Armvirt 64
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
            Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
